version: "3"

services:
  python:
    build:
      context: .
      dockerfile: ./python/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    environment:
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - DB_TABLE
    tty: true

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "mysql"]
            timeout: 20s
            retries: 10
