version: "3"

services:
  python:
    build:
      context: .
      dockerfile: ./python/Dockerfile
    networks:
      - dbserver
    volumes:
      - type: bind
        source: ./python/lib
        target: /python/lib
      - type: bind
        source: ./python/test
        target: /python/test
    tty: true

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    expose:
      - $DB_PORT
    networks:
      - dbserver
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USERNAME=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD

networks:
  dbserver:

volumes:
  mysql:
