version: "3"

services:
  python:
    build:
      context: .
      dockerfile: ./python/Dockerfile
    depends_on:
      - mysql
    networks:
      - dbserver
    volumes:
      - type: bind
        source: ./python/lib
        target: /python/lib
      - type: bind
        source: ./python/test
        target: /python/test
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - DB_ROOT_PASSWORD
      - DB_TABLE
    tty: true

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - "3306:3306"
    networks:
      - dbserver
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE
      - MYSQL_USERNAME
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD

  wait:
    image: willwill/wait-for-it:latest

networks:
  dbserver:

volumes:
  mysql:
