version: "3"

services:
  appserver:
    build:
      context: .
      dockerfile: ./appserver/Dockerfile
    depends_on:
      dbserver:
        condition: service_healthy
    links:
      - dbserver
      - selenium_chrome
    environment:
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - SELENIUM_DRIVER_URL
    tty: true

  selenium_chrome:
    image: selenium/standalone-chrome-debug:latest
    logging:
      driver: none
    ports:
      - "4444:4444"

  batch:
    build:
      context: .
      dockerfile: ./batch/Dockerfile
    depends_on:
      dbserver:
        condition: service_healthy
    links:
      - dbserver
    environment:
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - DB_TABLE
    tty: true

  dbserver:
    build:
      context: .
      dockerfile: ./dbserver/Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "dbserver"]
      timeout: 20s
      retries: 10
