version: "3"

services:
  appserver:
    build:
      context: .
      dockerfile: ./appserver/Dockerfile
    command:
      bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - type: bind
        source: ./appserver
        target: /appserver
    ports:
      - 3000:3000
    depends_on:
      - dbserver
      - selenium_chrome
    networks:
      - dbservernetwork
      - browsernetwork
    env_file:
      - ./.env
    stdin_open: true
    tty: true

  # システムテスト用
  selenium_chrome:
    image: selenium/standalone-chrome-debug:latest
    logging:
      driver: none
    ports:
      - "4444:4444"
    networks:
      - browsernetwork

  batch:
    build:
      context: .
      dockerfile: ./batch/Dockerfile
    command: >
      sh -c "cd lib && python main.py && /bin/bash"
    networks:
      - dbservernetwork
    depends_on:
      - dbserver
    volumes:
      - type: bind
        source: ./batch/lib
        target: /python/lib
      - type: bind
        source: ./batch/test
        target: /python/test
    env_file:
      - ./.env
    tty: true

  dbserver:
    build:
      context: .
      dockerfile: ./dbserver/Dockerfile
    expose:
      - 3306
    networks:
      - dbservernetwork
    volumes:
      - dbserver:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USERNAME=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - TZ=Asia/Tokyo

networks:
  dbservernetwork:
  browsernetwork:

volumes:
  dbserver:
