name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose up
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
          DB_HOST: dbserver
          DB_PORT: 3306
          DB_DATABASE: test
          DB_USERNAME: root
          DB_PASSWORD: password
          DB_TABLE: indicators
        run: |
          docker-compose -f docker-compose.ci.yml up -d --remove-orphans

      - name: Run Lint
        run : |
          docker exec -i kabucalculator_batch_1 bash -c "python -m flake8 test lib --exclude python3.9 && exit"

      - name: Run Tests
        run: |
          docker exec -i kabucalculator_batch_1 bash -c "cd test && python -m unittest"
