name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose up
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: test
          DB_USERNAME: root
          DB_PASSWORD: password
          DB_TABLE: indicators
        run: |
          docker-compose up -d --remove-orphans

      - name: Run Tests
        run: |
          docker exec -i kabucalculator_python_1 bash -c "cd test && python -m unittest"
