name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test with docker-compose stack
        run: |
          docker-compose up -d --remove-orphans
          docker exec -i kabucalculator_python_1 bash -c "cd test && python -m unittest"
